export { reverseGeocode, getDirections } from "./google-services";
export { apiLogin, changePassword, deleteAccount } from "./auth";
export { getDashCounts } from "./common";
export {
  getDevicesList,
  addDevice,
  getVehicleList,
  addVehicle,
  deleteVehicle,
  updateVehicle,
  getVehicleById,
  getPoiList,
  deletePoi,
  addPoi,
  updatePoi,
  getFuelTypes,
  getNotificationsList,
  createGeoFence,
  updateGeoFence,
  deleteGeoFence,
  getGeoFenceById,
  getGeoFenceByDeviceId,
  getGeoFenceList,
} from "./devices-vehicles";
export {
  getServiceCounts,
  getServices,
  getServiceTypes,
  addService,
  getServiceStatus,
  updateServiceStatus,
  deleteService,
} from "./service";
export {
  getDrivers,
  getDriverById,
  addDriver,
  deleteDriver,
  updateDriver,
  assignVehicles,
  getAssignedVehicles,
  addDriverBehavior,
  getDriverBehaviorByDriverId,
  getBehaviorEventTypes as getEventTypes,
  addTask,
  endTask,
  getCheckList,
  getTaskList,
  qrScanDeviceDetails,
} from "./drivers";
