import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const theme = {
  img: {
    size: {
      md: {
        height: 80,
        width: 80,
      },
      lg: {
        height: 125,
        width: 125,
      },
    },
  },
  header: {
    height: 45,
  },
  font: {
    thin: "Visby-Thin",
    light: "Visby-Light",
    regular: "Visby-Regular",
    medium: "Visby-Medium",
    bold: "Visby-Bold",
    heavy: "Visby-Heavy",
  },
  fontSize: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 18,
    xl: 24,
  },
  radius: {
    none: 0,
    xs: 6,
    sm: 8,
    md: 12,
    lg: 15,
    xl: 18,
    full: 9999,
  },
  spacing: {
    none: 0,
    xs: 4,
    sm: 6,
    md: 8,
    lg: 12,
    xl: 15,
    xxl: 20,
    xxxl: 25,
  },
  colors: {
    transparent: "transparent",
    dark: [
      "#C1C2C5",
      "#A6A7AB",
      "#909296",
      "#5C5F66",
      "#373A40",
      "#2C2E33",
      "#25262B",
      "#1A1B1E",
      "#141517",
      "#101113",
    ],
    gray: [
      "#F8F9FA",
      "#F1F3F5",
      "#E9ECEF",
      "#DEE2E6",
      "#CED4DA",
      "#ADB5BD",
      "#868E96",
      "#495057",
      "#343A40",
      "#212529",
    ],
    red: [
      "#FFF5F5",
      "#FFE3E3",
      "#FFC9C9",
      "#FFA8A8",
      "#FF8787",
      "#FF6B6B",
      "#FA5252",
      "#F03E3E",
      "#E03131",
      "#C92A2A",
    ],
    pink: [
      "#FFF0F6",
      "#FFDEEB",
      "#FCC2D7",
      "#FAA2C1",
      "#F783AC",
      "#F06595",
      "#E64980",
      "#D6336C",
      "#C2255C",
      "#A61E4D",
    ],
    grape: [
      "#F8F0FC",
      "#F3D9FA",
      "#EEBEFA",
      "#E599F7",
      "#DA77F2",
      "#CC5DE8",
      "#BE4BDB",
      "#AE3EC9",
      "#9C36B5",
      "#862E9C",
    ],
    violet: [
      "#F3F0FF",
      "#E5DBFF",
      "#D0BFFF",
      "#B197FC",
      "#9775FA",
      "#845EF7",
      "#7950F2",
      "#7048E8",
      "#6741D9",
      "#5F3DC4",
    ],
    indigo: [
      "#EDF2FF",
      "#DBE4FF",
      "#BAC8FF",
      "#91A7FF",
      "#748FFC",
      "#5C7CFA",
      "#4C6EF5",
      "#4263EB",
      "#3B5BDB",
      "#364FC7",
    ],
    blue: [
      "#E7F5FF",
      "#D0EBFF",
      "#A5D8FF",
      "#74C0FC",
      "#4DABF7",
      "#339AF0",
      "#228BE6",
      "#1C7ED6",
      "#1971C2",
      "#1864AB",
    ],
    cyan: [
      "#E3FAFC",
      "#C5F6FA",
      "#99E9F2",
      "#66D9E8",
      "#3BC9DB",
      "#22B8CF",
      "#15AABF",
      "#1098AD",
      "#0C8599",
      "#0B7285",
    ],
    teal: [
      "#E6FCF5",
      "#C3FAE8",
      "#96F2D7",
      "#63E6BE",
      "#38D9A9",
      "#20C997",
      "#12B886",
      "#0CA678",
      "#099268",
      "#087F5B",
    ],
    green: [
      "#EBFBEE",
      "#D3F9D8",
      "#B2F2BB",
      "#8CE99A",
      "#69DB7C",
      "#51CF66",
      "#40C057",
      "#37B24D",
      "#2F9E44",
      "#2B8A3E",
    ],
    lime: [
      "#F4FCE3",
      "#E9FAC8",
      "#D8F5A2",
      "#C0EB75",
      "#A9E34B",
      "#94D82D",
      "#82C91E",
      "#74B816",
      "#66A80F",
      "#5C940D",
    ],
    yellow: [
      "#FFF9DB",
      "#FFF3BF",
      "#FFEC99",
      "#FFE066",
      "#FFD43B",
      "#FCC419",
      "#FAB005",
      "#F59F00",
      "#F08C00",
      "#E67700",
    ],
    orange: [
      "#FFF4E6",
      "#FFE8CC",
      "#FFD8A8",
      "#FFC078",
      "#FFA94D",
      "#FF922B",
      "#FD7E14",
      "#F76707",
      "#E8590C",
      "#D9480F",
    ],
  },
} as const;

export const globalStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    paddingTop: theme.spacing.none,
    paddingHorizontal: theme.spacing.lg,
    backgroundColor: colors.mediumGray,
  },
  card: {
    borderRadius: theme.radius.md,
    marginVertical: theme.spacing.xs,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    rowGap: theme.spacing.sm,
    backgroundColor: colors.white,
    // borderWidth: 1,
  },
  tblHeaderText: {
    color: colors.titleText,
    fontFamily: theme.font.bold,
    textAlignVertical: "top",
    fontSize: theme.fontSize.sm,
    // borderWidth: 1,
  },
  tblDescText: {
    color: colors.titleText,
    fontFamily: theme.font.medium,
    textAlignVertical: "top",
    fontSize: theme.fontSize.sm,
    // borderWidth: 1,
  },
  buttonLabelTextAddOn: {
    //tblDescText
    letterSpacing: 0.5,
  },
  headerText: {
    fontFamily: theme.font.heavy,
    textAlign: "center",
    flexWrap: "wrap",
    fontSize: theme.fontSize.xl,
    color: colors.titleText,
  },
  cardInfoTitleText: {
    fontFamily: theme.font.bold,
    fontSize: theme.fontSize.lg,
    color: colors.titleText,
    textAlign: "left",
    textAlignVertical: "top",
    // borderWidth: 1,
  },
  cardTitleText: {
    fontSize: theme.fontSize.lg,
    fontFamily: theme.font.medium,
    color: colors.titleText,
  },
  descText: {
    fontFamily: theme.font.medium,
    fontSize: theme.fontSize.md,
    color: colors.qtyTextGray,
  },
  descTextBold: {
    fontFamily: theme.font.bold,
    fontSize: theme.fontSize.md,
    color: colors.qtyTextGray,
  },
  descTextPrimaryBold: {
    fontFamily: theme.font.bold,
    fontSize: theme.fontSize.md,
    // textAlign: "center",
    textAlignVertical: "center",
    color: colors.primary,
  },
  formErrorText: {
    fontFamily: theme.font.medium,
    fontSize: theme.fontSize.sm,
    color: colors.error,
  },
  descTextPrimary: {
    fontFamily: theme.font.medium,
    fontSize: theme.fontSize.md,
    textAlign: "center",
    color: colors.primary,
  },
  fab: {
    position: "absolute",
    margin: theme.spacing.xl,
    right: theme.spacing.none,
    bottom: theme.spacing.none,
    elevation: 8,
    backgroundColor: colors.primary,
  },
});
